# Generated by Django 4.0.3 on 2022-03-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oid', models.IntegerField()),
                ('oname', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('mfg', models.DateTimeField()),
            ],
        ),
    ]
