# Generated by Django 4.0.3 on 2022-03-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mfg',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
